namespace:
  name: staging

nodeserver:
  name: node-server

  image:
    name: node-server
    tag: v1
    exposedPort: 3000

  replicas: 3

  env:
    NODE_ENV: production

  service:
    type: ClusterIP

nginxserver:
  name: nginx-server

  image:
    name: nginx-server
    tag: v1
    exposedPort: 80

  replicas: 3

  service:
    type: LoadBalancer